# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-19 21:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('time_uploaded', models.DateTimeField(verbose_name=datetime.datetime(2016, 3, 19, 21, 30, 27, 161000, tzinfo=utc))),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
