# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='time_uploaded',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 3, 19, 21, 43, 36, 770565, tzinfo=utc)),
        ),
    ]
