# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20160319_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='time_uploaded',
        ),
    ]
