# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20160319_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='lol', max_length=500),
        ),
    ]
