# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_file_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='UploadedFile',
        ),
    ]
