# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_remove_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='docfile',
        ),
    ]
