# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_auto_20160321_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='docfile',
            new_name='file',
        ),
    ]
