# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0010_auto_20160321_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='default name.', max_length=500),
            preserve_default=False,
        ),
    ]
