# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0011_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='time_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 10, 29, 8, 453864, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
