# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0012_file_time_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 3, 23, 10, 35, 25, 633510, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='time_uploaded',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
