# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0014_auto_20160323_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
