# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0015_auto_20160323_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
