# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0016_file_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='urlname',
            field=models.CharField(default='LOL', max_length=10),
            preserve_default=False,
        ),
    ]
