# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0019_file_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 24, 20, 16, 37, 708436, tzinfo=utc)),
        ),
    ]
